-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Profiles table (extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  role text default 'client' check (role in ('client', 'tasker', 'admin')),
  phone text,
  address text,
  bio text
);

-- Turn on RLS
alter table public.profiles enable row level security;

-- Create policies for Profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create trigger to auto-create profile on signup
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create Bookings table
create table public.bookings (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id),
  service_type text not null,
  description text,
  location text not null,
  scheduled_at timestamp with time zone not null,
  status text default 'pending' check (status in ('pending', 'assigned', 'in_progress', 'completed', 'cancelled')),
  price decimal(10,2),
  contact_name text,
  contact_phone text
);

-- Turn on RLS for Bookings
alter table public.bookings enable row level security;

-- Policies for Bookings
create policy "Users can view their own bookings."
  on bookings for select
  using ( auth.uid() = user_id );

create policy "Users can create bookings."
  on bookings for insert
  with check ( auth.uid() = user_id );

create policy "Admins/Taskers can view all bookings (simplified for demo)"
  on bookings for select
  using ( true ); -- In production, strictly filter this!

-- Create Categories table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  icon_name text
);

alter table public.categories enable row level security;

create policy "Categories are viewable by everyone"
  on categories for select
  using ( true );
